server:
  port: 8001

spring:
  application:
    name: shopmall-manager
  main:
    allow-circular-references: true
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/分钟
code:
  expiration: 5

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAKzZAuttX8TVf7snv75m10paATbbwjhY+/uiDhHf6QbzzhkP+AAJjPUQTwlik//b6c/ZBFr2gcRyEa0f/2EJbiI1HConlRPYybPluyDjSVyp3MqvxSJw+vusOA+0jd4XdLboenf6ROVVcH1S69fV1TcM7O+NezZwxU8/8EGvoPZxAgMBAAECgYAi9fby9wm0pqliCdFs+eCoa4mM1sjTPF5lYHsfju5Th2tDovj6yvO9mrmd0JhWW10Quxi4LF2FhjwAjDULo8xoXiWg4Uu8gwqT/IeA8XomXTO/U+J2y7lIRNgCIzAgDhSZ7k6HsEM4F/gjQDt43OY6qRwuam9xGLHhs0+7Zz44RQJBAN3nkAaFHv7emibl6STz+Y9fuHYtd0cpTcbypTrte4ryvejOPscZnHjZF2Yjl6Qax8dgqOKh7RoG0CVwtatX3N0CQQDHZ9ZXffQrga713laq9OQeKRwtjiJsXPhMhPft+7pQlopEpwiIKOg6hHo4TIiqmkYIf/CUiTxvf4kM7EV+RkylAkEAzb8vtivl4lDJQzm3IzEnej05TjG3v35XhBhlBS8+dkW9ucbJRFfF0fMPk/96UYkXJRDFZmTW72PTyHMprnXn7QJAD+XWb+lJ00ImmdGdJUoa+dCbP4KKegs7fJZJUf70zsIByhFrG7fvM+Ml/2ESsE9WcA0LODxsxhLr8UzRCY0/RQJAMQcs9hGkQXj5SU6TtFONHqZR7vk2NzKPnKXOBPQbpEk2hJQ8QDfYVcVsCokqd/m9PxjPN4Ks36a2oHHgln9pDg==
# sm.ms 图床的 token
smms:
  token: 1oOP3ykFDI0K6ifmtvU7c8Y1eTWZSlyl

shopmall:
  # 配置
  version: 1.0
  apiUrl: http://127.0.0.1:8009/api

logging:
  level:
    com.shopmall: TRACE
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

mybatis-plus:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      mapper-locations: classpath:mapper/**/*Mapper.xml
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
